# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peds', models.IntegerField(default=39998)),
                ('cams', models.IntegerField(default=40)),
                ('mics', models.IntegerField(default=41)),
                ('temps', models.IntegerField(default=20)),
                ('analysis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=50)),
                ('favorites', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=300)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=600)),
                ('score', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=300)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
