# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171014_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
