# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171014_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peds', models.IntegerField(default=39998)),
                ('cams', models.IntegerField(default=40)),
                ('mics', models.IntegerField(default=41)),
                ('temps', models.IntegerField(default=20)),
            ],
        ),
    ]
